branches:
  only:
    - master
before_install:
  - sudo apt-get install -y rsync
script: 
  - echo -n $travisci_{00..30} >> ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host ci.progrium.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - rsync -avz --exclude ".git" -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" . gitreceive@ci.progrium.com:.
  - ssh gitreceive@ci.progrium.com make test

#notifications:
#  irc: "chat.freenode.net#dokku"
env:
  global:
    - secure: "CnUscGcLAp70E0Ok8mYjvRwbixG7SXA0wSqWCUH4L7bWr+anqtARFyIrPJXX\nTA0IfjqwhrJ72ToD3srmBKt+cp1vWaOnVbyUoGviMg2dLRayJxF/24/F5ROZ\ntuUinUlRTo3h0zu03lmcJVN1yl9jVi/7aukBUSQQNEcW52dB3a4="
    - secure: "Dx2tppnkY4wDiOU+vsQF860/t8du67YzhDm3Yb8e90R7bD7bnJ444/I0Ezel\noCO0u/RzQsaS2Ms6QO1xDcle2Cl6p+Il78nAdPdpePWlMhVzKXIYvAbDJCP3\nXl04CVY4svyCLIk3Gga9T9/21O7NoDLZXwg4sg4bOaAB+G0nNkY="
    - secure: "GcBV4OoIMUgE4kAOEdI+EPuGdGjsloRuDL0EjI1Lc7PoT3icf3xLr2FB+l+g\nvJTG4CHEY4aLfOkCOA44vJZ0cvHUisqv/mC08yCg39jtw6KUQSg18HcfTX/u\nX0HXKPXWMcIEmjhvUgUONmBonV2gwcPMYkENhQy3l0Uec3jwomc="
    - secure: "F932CiYdF76bzMDBwPFPHDJhfNkAEIJe98YNPQxgyj59SHlVHvgs2ySmdZZy\n/lIqxD1CgFeewMmYrTnUM5BKHjoLOKJqYI3KkSoRy1aUpKb5o1jtNS/049mj\ntG01VMT/Lk0r37+a7tYCXhbJ81z/mmWVucIKjASO5Pyb8NieLRI="
    - secure: "CfR2n51kb5KPdqYCUtXA/sM2BPF6XcWltX1MPQiQmU690RaYGThNM+y1Uhub\nMBjc7s85ejmX23b7TgY6biVheu/EWSBlnkUt88aubQZTZ4LZDCKyHpaJB4hU\nWEVKUUVG1M2VI6atV1VMzI/VOe6KhZ9OhWMvQBkXTSCijTtYDO0="
    - secure: "IZBTzMB/hV/d8cspbu+Lm+J/70slbJP7VFXh007zJZtBabQvQAJMyu9RGy1A\nAW425UKC/3ogQ/xNPGaBsgeoDpwpIR8iZXAOrlzAKc3vKnv3YYAfZ7o9J1Y2\nTO1RLEmosO4PFPKkVFzsJJjbtiTz508Ak5fHokXY9nT8ouVOs48="
    - secure: "amC03pSIqrIUx92Yap39FggdXxgA9QOtslXeIeZJMWerCR8/J8FYA78KZzvV\ngftT6yM8z6sq3Z4Rpu13Ci9OGUsFEz2FYUITze8rVAZXTBOy9ht4XzDlV+kA\n/NJ5OICev3o+Ra5WnSJw1rGoWzVWn4sJBPWss1s3mYas+6zdaE8="
    - secure: "cs2+mY/ITTGHOp4W4FDbDRbtlyFkHGiyoMSWG4qLj3++ks//HTg7We39TkgR\nGZbgityJdeltN9t8D6i6ScxrFb6Rgcehq1ep735VCXlvq+0zYk2jUegdWLSp\n7cHuvSmICpT9UBLygdgrO4gaAaEXmsLMjqtkWwPZcv6kj0rMNvg="
    - secure: "Y5V/H1IKTJUtELAZrAqVi6eF+lQJ6poDUAZm9uq9dO2bnqSg0XncH4EXOWeZ\nljqxyZxJKrUTMWpG+wDT6YZkoCvq3w9Zxo9Fo1GSpSwjpUxGv0skJHE+sJw9\n2huXswmDXAdV7kRCLOBC/rvfzy9P/r4xOYG4meqIo/wb01LJ284="
    - secure: "QXvf5yWs6dUP0JOpK1Revpbho5/oEhJa0lmYxZYP+b+YU66Pf6SoXSX2Dunj\n4kr0LqtUhq0JOkkJnNvop1dWiUf65RNkNKEr423GSu6Ic1d9xxBhuRnZaocQ\niCEJbPQSlX/nSwRDxkvDdNyQxKwXDB2Vj/cIbVyAa+cuiXooGbM="
    - secure: "YP6RtpAjkFHih66jPRyyosLGXITPrvnubkpAyVYghn+cs9jA8/nWujrERqtL\nkYwIe5Evzhyc1GvMyDRWAWh7mY6F9gp5Q1TEwfFGRZlN2n7iTb6dQNcE8Kbk\nJhFbI1AzyyYAe+Iwokj1jjHwfVfsTHC6lwyPoEPXeOjIC4B2lwk="
    - secure: "WUQL8me3Eyp8dpix7ERgJeUTUOZPbsqWY82uJ6PtiCROF1axriEfw+VtnNrF\nq3QvHBXFWj568afPaJ8a3Lv8mdnZYgr3RWWbT04zyF3fW2XHbTRGNDJfqIG6\n/qzMRBgFJHbwBjzyFyYQlYx6HbsphUQRVtAbmhzKdC0oZsDigHw="
    - secure: "YPScmVVUr7qEQZMd1/J5/lwETAgOvpgb77nAJIWStwsZ/Iq73Jh4grAFxAV+\nJttuw4AZOTqz5l5ggNtvBxKfSrYOYWCY7x+91IZb8Fo6MbzAETi2j7ho3Eh2\n1XbCWUTkv5RtLkO2gT8Fahtfc9x4zTnJuk02HC5f/0R+zMAZ01U="
    - secure: "ggRiVqKFZ5bu/5tBMvJ7AECeDSN1BYU/hObC3MjZCGVn6uQwtLK081CHRWXz\nnQCNm0F1yksGUOiVbsqqOVJ/nn3TtS3SVbETeiCW7QrIHfYK6+P4a6Z4MhWX\nI4SnlxYSRW5IQHkmo40n8Xg/d8167wjlsoeIoMkZAb4RFP3xRIg="